<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <!--
      前端代码异常监控：
      https://zhuanlan.zhihu.com/p/31979395
    -->
    <script>
      ~(function () {
        // 捕获 异步 或 语法错误
        window.addEventListener("error", (e) => {
          console.log("window addEventListener error: ", e);
        });
      })();
      // 捕获 Promise 错误
      window.addEventListener("unhandledrejection", function (e) {
        e.preventDefault();
        console.log("Promise error: ", e.reason);
        return true;
      });
    </script>
    <!--
      对于 Javascript 而言，我们面对的仅仅只是异常，
      异常的出现不会直接导致 JS 引擎崩溃，最多只会使当前执行的任务终止。

      1、当前代码块将作为一个任务压入任务队列中，JS 线程会不断地从任务队列中提取任务执行。
      2、当任务执行过程中出现异常，且异常没有捕获处理，则会一直沿着调用栈一层层向外抛出，最终终止当前任务的执行。
      3、JS 线程会继续从任务队列中提取下一个任务继续执行。
    -->
    <script>
      ~(function () {
        console.log(a);
      })();
    </script>
    <img
      src="http://t8.baidu.com/it/u=1484500186,1503043093&fm=79&app=86&f=JPEG?w=1280&h=853"
      alt=""
    />
    <script>
      ~(function () {
        var b = 2;
        console.log(2);
      })();
    </script>
    <script>
      ~(function () {
        setTimeout(() => {
          console.log(c);
        }, 1000);
      })();
    </script>

    <script>
      ~(function () {
        setTimeout(() => {
          Promise.reject("promise reject");
        }, 2000);
      })();
    </script>
  </body>
</html>
